In [1]:
import numpy as np
a = np.zeros(25)

In [2]:
inputs = []

In [3]:
outputs = [1, -1, -1, -1, -1]

In [4]:
a-=1

In [7]:
a1 = np.zeros(25) - 1
a2 = np.zeros(25) - 1
a3 = np.zeros(25) - 1
a4 = np.zeros(25) - 1
a5 = np.zeros(25) - 1
a6 = np.zeros(25) - 1

In [8]:
'''
c
'''
for i in range(1, 5):
    a1[i] = 1
for i in range(5, 16, 5):
    a1[i] = 1
for i in range(21, 25):
    a1[i] = 1

In [9]:
a1

array([-1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1., -1., -1.,
       -1., -1.,  1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.])

In [10]:
#o
for i in range(1, 4):
    a2[i] = 1
for i in range(5, 16, 5):
    a2[i] = 1
for i in range(9, 20, 5):
    a2[i] = 1
for i in range(21, 24):
    a2[i] = 1

In [11]:
a2

array([-1.,  1.,  1.,  1., -1.,  1., -1., -1., -1.,  1.,  1., -1., -1.,
       -1.,  1.,  1., -1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.])

In [12]:
#D
for i in range(0, 4):
    a3[i] = 1
for i in range(5, 16, 5):
    a3[i] = 1
for i in range(20, 24):
    a3[i] = 1
for i in range(9, 20, 5):
    a3[i] = 1

In [13]:
a3

array([ 1.,  1.,  1.,  1., -1.,  1., -1., -1., -1.,  1.,  1., -1., -1.,
       -1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1.])

In [14]:
#F
for i in range(0, 5):
    a4[i] = 1
for i in range(5, 21, 5):
    a4[i] = 1
for i in range(10, 15):
    a4[i] = 1

In [15]:
a4

array([ 1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,  1.,  1.,
        1.,  1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.])

In [16]:
#E
for i in range(0, 5):
    a5[i] = 1
for i in range(5, 21, 5):
    a5[i] = 1
for i in range(21, 25):
    a5[i] = 1
for i in range(10, 15):
    a5[i] = 1

In [17]:
a5

array([ 1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,  1.,  1.,
        1.,  1.,  1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
inputs.append(a1)
inputs.append(a2)
inputs.append(a3)
inputs.append(a4)
inputs.append(a5)

In [19]:
weights = np.zeros(25)

In [20]:
weights

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
bias = 0

In [22]:
epochs = 10
alpha = 1

In [23]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [24]:
target = np.zeros(len(inputs))

In [29]:
for e in range(epochs):
    #print("epoch" + str(e))
    for i in range(len(inputs)):
        out = np.matmul(inputs[i], weights) + bias
        #print(out)
        '''out_sigmoid = sigmoid(out)
        if out_sigmoid > 0.85:
            y=1
            print(i)
        else:
            y=0
        if y == outputs[i]:
            target[i] = outputs[i]
        else:
            loss = abs(outputs[i] - out_sigmoid)
            bias += alpha*outputs[i]
            weights += alpha*inputs[i]*outputs[i]'''
        out = sigmoid(out)
        #print(out)
        if out>0.75:
            y = 1
        else:
            y = -1
        if y!=outputs[i]:
            #print(out)
            del_w = alpha*outputs[i]*inputs[i]
            del_b = alpha*outputs[i]
            weights += del_w
            bias += del_b
    #print(loss)

In [30]:
weights

array([-1., -1., -1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1., -1.,
       -1., -3., -1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  3.])

In [31]:
bias

-1

In [32]:
for i in range(0, 5):
    a6[i] = 1
for i in range(5, 16, 5):
    a6[i] = 1
for i in range(20, 25):
    a6[i] = 1

In [33]:
out_test = np.matmul(a6, weights) + bias

In [34]:
out_test

2.0

In [35]:
out_sig = sigmoid(out_test)

In [36]:
out_sig

0.8807970779778823

In [37]:
def predict(x):
    out_test_predict = np.matmul(x, weights) + bias
    sig_out_test_predict = sigmoid(out_test_predict)
    if(sig_out_test_predict > 0.85):
        print("It's a match")
    else:
        print("It isn't a match")

In [38]:
predict(a1)

It's a match


In [39]:
predict(a4)

It isn't a match


In [40]:
predict(a2)

It isn't a match


In [41]:
predict(a3)

It isn't a match


In [42]:
predict(a5)

It isn't a match


In [43]:
predict(a6)

It's a match


In [44]:
a_test = np.ones(25)
predict(a_test)

It isn't a match
